name: Build

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: The Optimize Controller image tag
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Need to use a PAT so this will trigger the release action
          token: ${{ secrets.BMASTERS_TOKEN }}
      - name: Build Chart
        env:
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
          GIT_COMMITTER_NAME: Butch Masters
          GIT_COMMITTER_EMAIL: b-masters@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |-
          msg="$(./build.sh)"
          if git commit -am "${msg}" ; then
            git push
          else
            echo "::warning title=No changes::There were no changes made by this build."
          fi
